# name you can give any name
name: Continuous Integration and Continuous Deployment on Heroku

# triggers ci cd when you push code to any branch
on:
  push:
  pull_request:
  # this is for manual trigger of ci cd workflow from github actions
  workflow_dispatch:

# jobs is the place where you define all the steps
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      # install nodejs
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # install dependencies
      - name: Install Dependencies
        run: npm install

      # run linters
      - name: Run Linters
        run: npm run lint

      # run formater
      - name: Run Formater
        run: npm run format

      # verify the commit message with commitlint and commitlint.config.js
      - name: Verify Commit Message
        uses: wagoid/commitlint-github-action@v3
        with:
          configFile: commitlint.config.cjs

      # build docker image for ci cd pipeline
      # Name should be same as the name of the image in docker-compose.yml file with tag 1.0 and . represents the path of the dockerfile in the repo.
      - name: Build Docker Image
        run: docker build -t nextjs-cicd-docker:1.0 .

  # add another job for deployment
  deploy:
    name: Deploy to Heroku

    # this job will run only when the build-and-test job is successful
    needs: build-and-test

    # if condition is because we want to run this job only when we push code to main branch and not on pull request or any other branch push or manual trigger. In ci we want ci to run on push and pull request but we want cd to run only on push to main branch.
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # presist credentials is false because we don't want to push the code to heroku from github actions. We want to push the code to heroku from heroku cli.
          persist-credentials: false

      # install all dependencies for heroku
      # install nodejs
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # install dependencies
      - name: Install Dependencies
        run: npm install

      # one is push our docker image for our project to docker hub or any other registry  platform like aws. And there we can release the image container to the heroku platform.
      # In order to configure our CD to heroku there are 2 ways
      # second is to we don't push to docker image to the dockerhub or any other registry platform. We push the docker image to the heroku platform directly. And release the image container to the heroku platform. This is what we are doing here.

      # first we build doker image this is not required if our image in docker hub or any other registry platform
      - name: Build Docker Image
        run: docker-compose up --build -d

      # push it to heroku directly
      - name: Login to the Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Tag and Push Docker Image to Heroku

        # nextjs-cicd-docker name will be using for heroku app name not the same as docker image name. we create nextjs-cicd-docker app later . It not required to be same or this is not belong to the docker image name. /web belongs to the service name in docker-compose.yml file.
        run:
          docker tag nextjs-cicd-docker:1.0 registry.heroku.com/nextjs-cicd-docker/web
          docker push registry.heroku.com/nextjs-cicd-docker/web

        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # release the image container to the heroku platform
      - name: Release Docker Image to Heroku
        run: heroku container:release web -a nextjs-cicd-docker
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
